@baseUrl = http://shoppinglist-app.local

###
POST {{baseUrl}}/user/data

{
    "username": "Monsieur Bingo",
    "email": "bingomaster@gmail.com",
    "password": "BINGO!"
}


###

GET {{baseUrl}}/user/data

###

GET {{baseUrl}}/articles


###

GET {{baseUrl}}/shopping/lists