@baseUrl = http://shoppinglist-app.local

###
POST {{baseUrl}}/user/data

{
    "username": "Monsieur Bingo",
    "email": "bingomaster@gmail.com",
    "password": "BINGO!"
}

###

GET {{baseUrl}}/user/data

###

GET {{baseUrl}}/articles

###

GET {{baseUrl}}/shopping/lists/getAmountsFromShoppingLists/1/0
###

GET {{baseUrl}}/articles/itemsonshoppinglist/1/0

###