@baseUrl = http://shoppinglist-app.local/

###
GET {{baseUrl}}/game
Authorization: Bearer 5fbb89973681e5.67872682


###
GET {{baseUrl}}/user
Authorization: Bearer 5fbb89973681e5.67872682



###
POST {{baseUrl}}/game
Authorization: Bearer 5fbb89973681e5.67872682

{
    "round": 10
}


###
POST {{baseUrl}}/user_data

{
    "username": "Monsieur Bingo",
    "email": "bingomaster@gmail.com",
    "password": "BINGO!"
}


###

GET {{baseUrl}}/user_data

